receivers:
  otlp:
    protocols:
      http: {}        # apps -> collector via OTLP/HTTP (4318)

exporters:
  otlp:               # collector -> Jaeger via OTLP/gRPC (4317)
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]