services:
  discovery-server:
    build:
      context: .
      dockerfile: discovery-server/Dockerfile
    image: demo/discovery-server:1.0.0
    ports: ["8761:8761"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 20

  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    image: demo/inventory-service:1.0.0
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8081
    depends_on:
      discovery-server:
        condition: service_healthy
    ports: ["8081:8081"]

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    image: demo/order-service:1.0.0
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8082
    depends_on:
      discovery-server:
        condition: service_healthy
      inventory-service:
        condition: service_started
    ports: ["8082:8082"]

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    image: demo/api-gateway:1.0.0
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SERVER_PORT=8080
    depends_on:
      discovery-server:
        condition: service_healthy
      inventory-service:
        condition: service_started
      order-service:
        condition: service_started
    ports: ["8080:8080"]
