server:
  port: 8082
spring:
  application:
    name: order-service
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

# Resilience4j basic config
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 6 ## consider last 6 calls
        minimumNumberOfCalls: 4
        failureRateThreshold: 50 # if it reaches 50% consider it as open
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
  retry:
    instances:
      inventory:
        maxAttempts: 3 # straight attempt + retries 
        waitDuration: 200ms
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException

management:
  endpoints:
    web:
      exposure:
        include: health,info
