server:
  port: 8082
spring:
  application:
    name: order-service
eureka:
  client:
    service-url.defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
management:
  tracing.sampling.probability: 1.0
  otlp.tracing.endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}
  endpoints:
    web.exposure.include: health,info,metrics
