
spring:
  application:
    name: producer-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8080

app:
  topic:
    name: orders-topic

---
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: localhost:9092
