server:
  port: 8080

spring:
  application:
    name: metrics-demo

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        business.timer: true
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99
        business.timer: 0.5,0.9,0.99
    tags:
      application: ${spring.application.name}

# Turn on exemplars when supported (Propagates trace id if available)
  tracing:
    enabled: true
