server:
  port: 8081
spring:
  application:
    name: inventory-service
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
management.endpoints.web.exposure.include: health,info
