# receivers:
#   otlp:
#     protocols:
#       http:
#       grpc:

# processors:
#   batch:

# exporters:
#   prometheus:
#     endpoint: "0.0.0.0:9464"        # must listen on all interfaces
#     send_timestamps: true
#     resource_to_telemetry_conversion:
#       enabled: true
#   otlp/jaeger:
#     endpoint: jaeger:4317
#     tls:
#       insecure: true

# service:
#   pipelines:
#     metrics:
#       receivers: [otlp]
#       processors: [batch]
#       exporters: [prometheus]       # <-- must include 'prometheus'
#     traces:
#       receivers: [otlp]
#       processors: [batch]
#       exporters: [otlp/jaeger]      # (if you’re sending traces to Jaeger)
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  logging:
    loglevel: info
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, logging]