services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: demo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpass@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongo

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mongodb-crud-demo:latest
    container_name: mongodb-crud-demo
    environment:
      MONGODB_URI: mongodb://mongo:27017/demo
      MONGODB_DATABASE: demo
    ports:
      - "18080:8080"
    depends_on:
      - mongo

volumes:
  mongo_data:
