version: "3.9"

services:
  web:
    image: nginx:alpine
    container_name: nginx-video
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./site:/usr/share/nginx/html:ro
    restart: unless-stopped