{
 "title": "Spring Boot JVM + HTTP + GC",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP requests per second by URI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (uri,method,status) (rate(http_server_requests_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "GC pause avg (last 5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum[5m]) / rate(jvm_gc_pause_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "GC pauses rate (events/s)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Heap memory used (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by (area) (jvm_memory_used_bytes{area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Process CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 20, "y": 4 },
   "targets": [
    { "expr": "process_cpu_usage" }
   ]
  },
  {
   "title": "Custom hello counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "demo_hello_requests_total" }
   ]
  }
 ]
}