server:
  port: 8080
spring:
  application:
    name: tracing-demo
  datasource:
    url: jdbc:postgresql://db:5432/appdb
    username: appuser
    password: apppass
    hikari:
      maximum-pool-size: 10
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
  metrics:
    tags:
      application: ${spring.application.name}
