server:
  port: 8761
spring:
  application:
    name: discovery-server
management:
  tracing.sampling.probability: 1.0
  otlp.tracing.endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}
  endpoints:
    web.exposure.include: health,info
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
