server:
  port: 8888

# spring:
#   application:
#     name: config-server
#   cloud:
#     config:
#       server:
#         # Use a simple file-based (native) repo for local dev
#         native:
#           search-locations: file:///mnt/data/java22-spring-config-demo/single-repo/config-repo
#         # To switch to Git, comment out 'native' above and use:
#         # git:
#         #   uri: file:///mnt/data/java22-spring-config-demo/single-repo/config-repo
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # relative to the *working directory* of the running process
          search-locations: file:../config-repo
management:
  endpoints:
    web:
      exposure:
        include: health,info
