receivers:
  otlp:
    protocols:
      http: {}
      grpc: {}

processors:
  batch: {}

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"
    send_timestamps: true
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
